version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - llm_service
    networks:
      - app-network

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - MCP_SERVER_URL=http://llm_service:3000/mcp
    networks:
      - app-network

  llm_service:
    build: ./llm_service
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge